import sys
from matplotlib.figure import Figure
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
# When replacing designer code remember to:
#   Only replace the code between begin and end
#   Change the icon url
#   Remove the main function
#   Set current index to 0

# Qt Designer
# Begin

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(914, 600)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("sev-cut.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QMainWindow {background-color: white}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.lapsSelectorPage = QtWidgets.QWidget()
        self.lapsSelectorPage.setObjectName("lapsSelectorPage")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.lapsSelectorPage)
        self.verticalLayout.setContentsMargins(20, 10, 20, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.lapsSelectorPage)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.deleteLabButton = QtWidgets.QPushButton(self.lapsSelectorPage)
        self.deleteLabButton.setMinimumSize(QtCore.QSize(0, 35))
        self.deleteLabButton.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(13)
        self.deleteLabButton.setFont(font)
        self.deleteLabButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deleteLabButton.setStyleSheet("background-color: #b3c5e5; \n"
"")
        self.deleteLabButton.setObjectName("deleteLabButton")
        self.horizontalLayout.addWidget(self.deleteLabButton)
        self.viewLabButton = QtWidgets.QPushButton(self.lapsSelectorPage)
        self.viewLabButton.setMinimumSize(QtCore.QSize(0, 35))
        self.viewLabButton.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.viewLabButton.setFont(font)
        self.viewLabButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.viewLabButton.setStyleSheet("background-color: #b3c5e5; \n"
"")
        self.viewLabButton.setObjectName("viewLabButton")
        self.horizontalLayout.addWidget(self.viewLabButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lapsList = QtWidgets.QListWidget(self.lapsSelectorPage)
        self.lapsList.setObjectName("lapsList")
        self.verticalLayout.addWidget(self.lapsList)
        self.stackedWidget.addWidget(self.lapsSelectorPage)
        self.DataViewPage = QtWidgets.QWidget()
        self.DataViewPage.setObjectName("DataViewPage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.DataViewPage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.page2_layout = QtWidgets.QVBoxLayout()
        self.page2_layout.setObjectName("page2_layout")
        self.tabWidget = QtWidgets.QTabWidget(self.DataViewPage)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.TableTab = QtWidgets.QWidget()
        self.TableTab.setObjectName("TableTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.TableTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableTab_layout = QtWidgets.QVBoxLayout()
        self.tableTab_layout.setObjectName("tableTab_layout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.TableTab)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.tableSelector = QtWidgets.QComboBox(self.TableTab)
        self.tableSelector.setMinimumSize(QtCore.QSize(0, 30))
        self.tableSelector.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tableSelector.setFont(font)
        self.tableSelector.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableSelector.setObjectName("tableSelector")
        self.tableSelector.addItem("")
        self.tableSelector.addItem("")
        self.tableSelector.addItem("")
        self.tableSelector.addItem("")
        self.tableSelector.addItem("")
        self.tableSelector.addItem("")
        self.tableSelector.addItem("")
        self.tableSelector.addItem("")
        self.horizontalLayout_2.addWidget(self.tableSelector)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.tableTab_layout.addLayout(self.horizontalLayout_2)
        self.tableWidget = QtWidgets.QTableWidget(self.TableTab)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableTab_layout.addWidget(self.tableWidget)
        self.tableTab_layout.setStretch(1, 1)
        self.gridLayout_3.addLayout(self.tableTab_layout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.TableTab, "")
        self.GraphTab = QtWidgets.QWidget()
        self.GraphTab.setObjectName("GraphTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.GraphTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.graphTab_layout = QtWidgets.QVBoxLayout()
        self.graphTab_layout.setObjectName("graphTab_layout")
        self.groupBox = QtWidgets.QGroupBox(self.GraphTab)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setContentsMargins(-1, -1, 4, 4)
        self.gridLayout_2.setVerticalSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkbox_minBatteryVoltage = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.checkbox_minBatteryVoltage.setFont(font)
        self.checkbox_minBatteryVoltage.setObjectName("checkbox_minBatteryVoltage")
        self.gridLayout_2.addWidget(self.checkbox_minBatteryVoltage, 0, 3, 1, 1)
        self.checkbox_motorCurrent = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.checkbox_motorCurrent.setFont(font)
        self.checkbox_motorCurrent.setObjectName("checkbox_motorCurrent")
        self.gridLayout_2.addWidget(self.checkbox_motorCurrent, 1, 0, 1, 1)
        self.checkbox_chargeRate = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.checkbox_chargeRate.setFont(font)
        self.checkbox_chargeRate.setObjectName("checkbox_chargeRate")
        self.gridLayout_2.addWidget(self.checkbox_chargeRate, 1, 1, 1, 1)
        self.checkbox_slaveMotorSpeed = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.checkbox_slaveMotorSpeed.setFont(font)
        self.checkbox_slaveMotorSpeed.setObjectName("checkbox_slaveMotorSpeed")
        self.gridLayout_2.addWidget(self.checkbox_slaveMotorSpeed, 1, 2, 1, 1)
        self.checkbox_masterMotorCurrent = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.checkbox_masterMotorCurrent.setFont(font)
        self.checkbox_masterMotorCurrent.setObjectName("checkbox_masterMotorCurrent")
        self.gridLayout_2.addWidget(self.checkbox_masterMotorCurrent, 0, 2, 1, 1)
        self.checkbox_batteryCurrent = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.checkbox_batteryCurrent.setFont(font)
        self.checkbox_batteryCurrent.setObjectName("checkbox_batteryCurrent")
        self.gridLayout_2.addWidget(self.checkbox_batteryCurrent, 0, 0, 1, 1)
        self.checkbox_maxBatteryVoltage = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.checkbox_maxBatteryVoltage.setFont(font)
        self.checkbox_maxBatteryVoltage.setObjectName("checkbox_maxBatteryVoltage")
        self.gridLayout_2.addWidget(self.checkbox_maxBatteryVoltage, 1, 3, 1, 1)
        self.checkbox_solarPanelsCurrent = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.checkbox_solarPanelsCurrent.setFont(font)
        self.checkbox_solarPanelsCurrent.setObjectName("checkbox_solarPanelsCurrent")
        self.gridLayout_2.addWidget(self.checkbox_solarPanelsCurrent, 2, 0, 1, 1)
        self.checkbox_DCBusVoltage = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.checkbox_DCBusVoltage.setFont(font)
        self.checkbox_DCBusVoltage.setObjectName("checkbox_DCBusVoltage")
        self.gridLayout_2.addWidget(self.checkbox_DCBusVoltage, 0, 1, 1, 1)
        self.checkbox_masterMotorSpeed = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.checkbox_masterMotorSpeed.setFont(font)
        self.checkbox_masterMotorSpeed.setObjectName("checkbox_masterMotorSpeed")
        self.gridLayout_2.addWidget(self.checkbox_masterMotorSpeed, 2, 1, 1, 1)
        self.checkbox_slaveMotorCurrent = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.checkbox_slaveMotorCurrent.setFont(font)
        self.checkbox_slaveMotorCurrent.setObjectName("checkbox_slaveMotorCurrent")
        self.gridLayout_2.addWidget(self.checkbox_slaveMotorCurrent, 2, 2, 1, 1)
        self.checkbox_maxBatteryTemperature = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.checkbox_maxBatteryTemperature.setFont(font)
        self.checkbox_maxBatteryTemperature.setObjectName("checkbox_maxBatteryTemperature")
        self.gridLayout_2.addWidget(self.checkbox_maxBatteryTemperature, 2, 3, 1, 1)
        self.checkbox_solarPanelsTemperature = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.checkbox_solarPanelsTemperature.setFont(font)
        self.checkbox_solarPanelsTemperature.setObjectName("checkbox_solarPanelsTemperature")
        self.gridLayout_2.addWidget(self.checkbox_solarPanelsTemperature, 3, 0, 1, 1)
        self.graphTab_layout.addWidget(self.groupBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.plotButton = QtWidgets.QPushButton(self.GraphTab)
        self.plotButton.setMinimumSize(QtCore.QSize(0, 30))
        self.plotButton.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.plotButton.setFont(font)
        self.plotButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.plotButton.setStyleSheet("background-color: #b3c5e5; \n"
"")
        self.plotButton.setObjectName("plotButton")
        self.horizontalLayout_3.addWidget(self.plotButton)
        self.graphTab_layout.addLayout(self.horizontalLayout_3)
        self.gridLayout_4.addLayout(self.graphTab_layout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.GraphTab, "")
        self.page2_layout.addWidget(self.tabWidget)
        self.verticalLayout_2.addLayout(self.page2_layout)
        self.stackedWidget.addWidget(self.DataViewPage)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SEV-CUT Monitoring"))
        self.label.setText(_translate("MainWindow", "Previously Monitored Laps:"))
        self.deleteLabButton.setText(_translate("MainWindow", "Delete Lap"))
        self.viewLabButton.setText(_translate("MainWindow", "View Lap"))
        self.label_2.setText(_translate("MainWindow", "Choose a table:"))
        self.tableSelector.setItemText(0, _translate("MainWindow", "Currents"))
        self.tableSelector.setItemText(1, _translate("MainWindow", "Bus Voltages"))
        self.tableSelector.setItemText(2, _translate("MainWindow", "Temperatures"))
        self.tableSelector.setItemText(3, _translate("MainWindow", "Batteries"))
        self.tableSelector.setItemText(4, _translate("MainWindow", "Master Motor"))
        self.tableSelector.setItemText(5, _translate("MainWindow", "Slave Motor"))
        self.tableSelector.setItemText(6, _translate("MainWindow", "Lights Status"))
        self.tableSelector.setItemText(7, _translate("MainWindow", "Switches Status"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TableTab), _translate("MainWindow", "Table Data"))
        self.groupBox.setTitle(_translate("MainWindow", "Items To Plot"))
        self.checkbox_minBatteryVoltage.setText(_translate("MainWindow", "Min Battery Voltage"))
        self.checkbox_motorCurrent.setText(_translate("MainWindow", "Motor Current"))
        self.checkbox_chargeRate.setText(_translate("MainWindow", "Charge Rate"))
        self.checkbox_slaveMotorSpeed.setText(_translate("MainWindow", "Slave Motor Speed"))
        self.checkbox_masterMotorCurrent.setText(_translate("MainWindow", "Master Motor Current"))
        self.checkbox_batteryCurrent.setText(_translate("MainWindow", "Battery Current"))
        self.checkbox_maxBatteryVoltage.setText(_translate("MainWindow", "Max Battery Voltage"))
        self.checkbox_solarPanelsCurrent.setText(_translate("MainWindow", "Solar Panels Current"))
        self.checkbox_DCBusVoltage.setText(_translate("MainWindow", "DC Bus Voltage"))
        self.checkbox_masterMotorSpeed.setText(_translate("MainWindow", "Master Motor Speed"))
        self.checkbox_slaveMotorCurrent.setText(_translate("MainWindow", "Slave Motor Current"))
        self.checkbox_maxBatteryTemperature.setText(_translate("MainWindow", "Max Battery Temperature"))
        self.checkbox_solarPanelsTemperature.setText(_translate("MainWindow", "Solar Panels Temperature"))
        self.plotButton.setText(_translate("MainWindow", "Plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.GraphTab), _translate("MainWindow", "Graph Data"))


# End


############################################
# Manually added code


class MainWindow(Ui_MainWindow):
    def __init__(self):
        self.main_window = QtWidgets.QMainWindow()
        self.setupUi(self.main_window)
        # Figure and Canvas of the graph
        self.graph_figure = Figure()
        self.graph_canvas = FigureCanvas(self.graph_figure)
        self.graphTab_layout.addWidget(self.graph_canvas)
        # Set the initial pages
        self.tableSelector.setCurrentIndex(-1)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)




