import sys
from matplotlib.figure import Figure
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
import numpy as np
# When replacing designer code remember to:
#   Only replace the code between begin and end
#   Change the icon url
#   Remove the main function
#   Set current index to 0

# Qt Designer
# Begin

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("GUI/sev-cut.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QMainWindow {background-color: white}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.lapsSelectorPage = QtWidgets.QWidget()
        self.lapsSelectorPage.setObjectName("lapsSelectorPage")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.lapsSelectorPage)
        self.verticalLayout.setContentsMargins(20, 10, 20, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.lapsSelectorPage)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.viewLabButton = QtWidgets.QPushButton(self.lapsSelectorPage)
        self.viewLabButton.setMinimumSize(QtCore.QSize(0, 35))
        self.viewLabButton.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.viewLabButton.setFont(font)
        self.viewLabButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.viewLabButton.setStyleSheet("background-color: #b3c5e5; \n"
"")
        self.viewLabButton.setObjectName("viewLabButton")
        self.horizontalLayout.addWidget(self.viewLabButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lapsList = QtWidgets.QListWidget(self.lapsSelectorPage)
        self.lapsList.setObjectName("lapsList")
        self.verticalLayout.addWidget(self.lapsList)
        self.stackedWidget.addWidget(self.lapsSelectorPage)
        self.DataViewPage = QtWidgets.QWidget()
        self.DataViewPage.setObjectName("DataViewPage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.DataViewPage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.page2_layout = QtWidgets.QVBoxLayout()
        self.page2_layout.setObjectName("page2_layout")
        self.tabWidget = QtWidgets.QTabWidget(self.DataViewPage)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.TableTab = QtWidgets.QWidget()
        self.TableTab.setObjectName("TableTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.TableTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableTab_layout = QtWidgets.QVBoxLayout()
        self.tableTab_layout.setObjectName("tableTab_layout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.TableTab)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.tableSelector = QtWidgets.QComboBox(self.TableTab)
        self.tableSelector.setMinimumSize(QtCore.QSize(0, 30))
        self.tableSelector.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tableSelector.setFont(font)
        self.tableSelector.setStyleSheet("bacground-color: white;")
        self.tableSelector.setObjectName("tableSelector")
        self.tableSelector.addItem("")
        self.tableSelector.addItem("")
        self.tableSelector.addItem("")
        self.tableSelector.addItem("")
        self.tableSelector.addItem("")
        self.tableSelector.addItem("")
        self.tableSelector.addItem("")
        self.tableSelector.addItem("")
        self.horizontalLayout_2.addWidget(self.tableSelector)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.tableTab_layout.addLayout(self.horizontalLayout_2)
        self.tableWidget = QtWidgets.QTableWidget(self.TableTab)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableTab_layout.addWidget(self.tableWidget)
        self.tableTab_layout.setStretch(1, 1)
        self.gridLayout_3.addLayout(self.tableTab_layout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.TableTab, "")
        self.GraphTab = QtWidgets.QWidget()
        self.GraphTab.setObjectName("GraphTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.GraphTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.graphTab_layout = QtWidgets.QVBoxLayout()
        self.graphTab_layout.setObjectName("graphTab_layout")
        self.scrollArea = QtWidgets.QScrollArea(self.GraphTab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 734, 506))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setContentsMargins(-1, -1, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_10 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_10.setFont(font)
        self.checkBox_10.setObjectName("checkBox_10")
        self.gridLayout_2.addWidget(self.checkBox_10, 0, 3, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout_2.addWidget(self.checkBox_7, 0, 2, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 0, 0, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_2.addWidget(self.checkBox_3, 1, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_2.addWidget(self.checkBox_2, 3, 0, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_2.addWidget(self.checkBox_4, 2, 0, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_8.setFont(font)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout_2.addWidget(self.checkBox_8, 1, 2, 1, 1)
        self.checkBox_9 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_9.setFont(font)
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout_2.addWidget(self.checkBox_9, 2, 2, 1, 1)
        self.checkBox_11 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_11.setFont(font)
        self.checkBox_11.setObjectName("checkBox_11")
        self.gridLayout_2.addWidget(self.checkBox_11, 1, 3, 1, 1)
        self.checkBox_13 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_13.setFont(font)
        self.checkBox_13.setObjectName("checkBox_13")
        self.gridLayout_2.addWidget(self.checkBox_13, 2, 1, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_2.addWidget(self.checkBox_6, 1, 1, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_2.addWidget(self.checkBox_5, 0, 1, 1, 1)
        self.checkBox_12 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_12.setFont(font)
        self.checkBox_12.setObjectName("checkBox_12")
        self.gridLayout_2.addWidget(self.checkBox_12, 2, 3, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.gridLayout_2.setColumnStretch(3, 1)
        self.gridLayout_2.setRowStretch(0, 1)
        self.gridLayout_2.setRowStretch(1, 1)
        self.gridLayout_2.setRowStretch(2, 1)
        self.gridLayout_2.setRowStretch(3, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.graphTab_layout.addWidget(self.scrollArea)
        self.gridLayout_4.addLayout(self.graphTab_layout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.GraphTab, "")
        self.page2_layout.addWidget(self.tabWidget)
        self.verticalLayout_2.addLayout(self.page2_layout)
        self.stackedWidget.addWidget(self.DataViewPage)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SEV-CUT Monitoring"))
        self.label.setText(_translate("MainWindow", "Select a lap to view:"))
        self.viewLabButton.setText(_translate("MainWindow", "View Lap"))
        self.label_2.setText(_translate("MainWindow", "Choose a table:"))
        self.tableSelector.setItemText(0, _translate("MainWindow", "Currents"))
        self.tableSelector.setItemText(1, _translate("MainWindow", "Bus Voltages"))
        self.tableSelector.setItemText(2, _translate("MainWindow", "Temperatures"))
        self.tableSelector.setItemText(3, _translate("MainWindow", "Batteries"))
        self.tableSelector.setItemText(4, _translate("MainWindow", "Master Motor"))
        self.tableSelector.setItemText(5, _translate("MainWindow", "Slave Motor"))
        self.tableSelector.setItemText(6, _translate("MainWindow", "Lights Status"))
        self.tableSelector.setItemText(7, _translate("MainWindow", "Switches Status"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TableTab), _translate("MainWindow", "Table Data"))
        self.checkBox_10.setText(_translate("MainWindow", "Min Battery Voltage"))
        self.checkBox_7.setText(_translate("MainWindow", "Master Motor Current"))
        self.checkBox.setText(_translate("MainWindow", "Battery Current"))
        self.checkBox_3.setText(_translate("MainWindow", "Motor Current"))
        self.checkBox_2.setText(_translate("MainWindow", "Solar Panels Temperature"))
        self.checkBox_4.setText(_translate("MainWindow", "Solar Panels Current"))
        self.checkBox_8.setText(_translate("MainWindow", "Slave Motor Speed"))
        self.checkBox_9.setText(_translate("MainWindow", "Slave Motor Current"))
        self.checkBox_11.setText(_translate("MainWindow", "Max Battery Voltage"))
        self.checkBox_13.setText(_translate("MainWindow", "Master Motor Speed"))
        self.checkBox_6.setText(_translate("MainWindow", "Charge Rate"))
        self.checkBox_5.setText(_translate("MainWindow", "DC Bus Voltage"))
        self.checkBox_12.setText(_translate("MainWindow", "Max Battery Temperature"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.GraphTab), _translate("MainWindow", "Graph Data"))



# End


############################################
# Manually added code

class MainWindow(Ui_MainWindow):
    def __init__(self):
        self.app = QtWidgets.QApplication(sys.argv)
        self.main_window = QtWidgets.QMainWindow()
        self.setupUi(self.main_window)
        self.graph_figure = Figure()
        self.graph_canvas = FigureCanvas(self.graph_figure)
        # Test



        # End Test
        self.graphTab_layout.addWidget(self.graph_canvas)
        # self.main_window.showMaximized()
        self.main_window.show()




